name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:

      - name: Checkout 
        uses: actions/checkout@v4
        
      - name: setup + cache
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      
      - name: security step
        env:
          PAROLA_MEA: ${{secrets.PAROLA_SECRETA}}
        run: |
          echo $PAROLA_MEA

      - name: Create an archive with my code
        run: zip -r aplicatie.zip app.py tests/

      - name: Release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release create ${{ github.ref_name }} aplicatie.zip --title "Release ${{ github.ref_name }}" --notes "Versiune automata-2"
